# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - MovieRecommendation

on:
  push:
    branches:
      - azure-deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://movierecommendation.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5e9ddbdaed0a433fb7f1bf18d54a716f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eda56f8699bc4fabafb1190fb9c438fc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: movierecommendation.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5e9ddbdaed0a433fb7f1bf18d54a716f }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MovieRecommendation'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0e5cfebcbfcc4672bddfefd911bf844b }}
        images: 'movierecommendation.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5e9ddbdaed0a433fb7f1bf18d54a716f }}/mltest:${{ github.sha }}'